services:

  mailhog:
    image: 'mailhog/mailhog:v1.0.0'
    ports:
      - '1025:1025' # SMTP port
      - '8025:8025' # REST port

  dynamodb:
    image: 'amazon/dynamodb-local'
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"
    ports:
      - '8000:8000'
    healthcheck:
      test: ["CMD-SHELL", '[ "$(curl -s -o /dev/null -I -w ''%{http_code}'' http://localhost:8000)" == "400" ]']
      interval: 1s
      timeout: 10s
      retries: 10

  aws-cli:
    image: 'amazon/aws-cli'
    user: root
    environment:
      AWS_ACCESS_KEY_ID: access
      AWS_SECRET_ACCESS_KEY: secret
      AWS_REGION: us-west-2
    volumes:
      - ./docker/dynamodb-init-script.sh:/scripts/dynamodb-init-script.sh
    entrypoint: ['bash']
    command: ["/scripts/dynamodb-init-script.sh"]
    depends_on:
      dynamodb:
        condition: service_healthy
      
