apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: seller-sphere/user-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: secret-access-key
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: aws-config
                  key: region
            - name: DYNAMODB_URL
              valueFrom:
                configMapKeyRef:
                  name: aws-config
                  key: dynamodb-url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: security
                  key: jwt-secret
            - name: MAIL_HOST
              value: "mailhog-local"
            - name: MAIL_PORT
              value: "1025"
