apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamodb-local-deployment
  namespace: default
  labels:
    app: dynamodb-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamodb-local
  template:
    metadata:
      labels:
        app: dynamodb-local
    spec:
      containers:
        - name: dynamodb-local
          image: amazon/dynamodb-local
          command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: dynamodb-local-service
spec:
  type: ExternalName
  externalName: dynamodb-local
  selector:
    app: dynamodb-local
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dynamodb-init-job
spec:
  template:
    spec:
      containers:
        - name: aws-cli
          image: amazon/aws-cli
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Ensure that DynamoDB has started
              until nc -z dynamodb-local 8000; do
                echo "Waiting for DynamoDB Local to startup...";
                sleep 5;
              done;

              # Create the tables
              aws dynamodb create-table \
                --table-name Users \
                --attribute-definitions AttributeName=PK,AttributeType=S \
                --key-schema AttributeName=PK,KeyType=HASH \
                --billing-mode PAY_PER_REQUEST \
                --endpoint-url http://dynamodb-local:8000
              
              echo "Created Tables!"
          restartPolicy: Never
